version: '3.8'

services:
  # PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: midas_postgres
    environment:
      POSTGRES_DB: midas_quant
      POSTGRES_USER: midas_user
      POSTGRES_PASSWORD: midas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - midas_network

  # Redis 캐시
  redis:
    image: redis:7-alpine
    container_name: midas_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - midas_network

  # InfluxDB 시계열 데이터베이스
  influxdb:
    image: influxdb:2.0
    container_name: midas_influxdb
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: midas_admin
      DOCKER_INFLUXDB_INIT_PASSWORD: midas_influx_password
      DOCKER_INFLUXDB_INIT_ORG: midas_org
      DOCKER_INFLUXDB_INIT_BUCKET: midas_bucket
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    networks:
      - midas_network

  # FastAPI 백엔드
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: midas_backend
    environment:
      - DATABASE_URL=postgresql://midas_user:midas_password@postgres:5432/midas_quant
      - REDIS_URL=redis://redis:6379
      - INFLUXDB_URL=http://influxdb:8086
      - ENVIRONMENT=development
      - BACKEND_HOST=0.0.0.0  # 외부 접근 허용
    ports:
      - "8000:8000"  # 외부에서 접근 가능
    volumes:
      - ./backend:/app
      - /app/__pycache__
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - midas_network
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # React 프론트엔드
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: midas_frontend
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - midas_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:
  influxdb_data:

networks:
  midas_network:
    driver: bridge